// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apps

import (
	"github.com/google/wire"
	"github.com/kumin/GolangMaster/restful/configs"
	"github.com/kumin/GolangMaster/restful/handler"
	"github.com/kumin/GolangMaster/restful/infras"
	"github.com/kumin/GolangMaster/restful/repos/mysql"
	"github.com/kumin/GolangMaster/restful/repos/provider"
	"github.com/kumin/GolangMaster/restful/services"
)

// Injectors from wire.go:

func BuildServer() (*HttpServer, error) {
	serverConfiguration := configs.NewServerConfiguration()
	mysqlConnector := infras.NewMysqlConnector()
	productMysqlRepo := mysql.NewProductMysqlRepo(mysqlConnector)
	productCtlServices := services.NewProductCtlServices(productMysqlRepo)
	productCtlHandler := handler.NewProductCtlHandler(productCtlServices)
	httpServer := NewHttpServer(serverConfiguration, productCtlHandler)
	return httpServer, nil
}

// wire.go:

var SuperGraphSet = wire.NewSet(provider.MysqlGraphSet, services.ServiceGraphSet, handler.HandlerGraphSet, ServerGraphSet)
